### Get all books
GET https://port4004-workspaces-ws-rmbjv.us10.trial.applicationstudio.cloud.sap/odata/v4/hanaservice/customer HTTP/1.1
### Create a book
POST https://port4004-workspaces-ws-rmbjv.us10.trial.applicationstudio.cloud.sap/odata/v4/hanaservice/customer HTTP/1.1
content-type: application/json

{
  "customerId": 5,
  "customerFirstName": "Wuthering",
  "customerLastName": "Heights",
  "address_adressId": "1001"
}
### Get the book
GET https://port4004-workspaces-ws-rmbjv.us10.trial.applicationstudio.cloud.sap/odata/v4/hanaservice/customer(customerId='001') HTTP/1.1
### Update the book
PATCH https://port4004-workspaces-ws-rmbjv.us10.trial.applicationstudio.cloud.sap/odata/v4/hanaservice/customer('1001') HTTP/1.1
content-type: application/json

{
  "author": "Emily Brontë"
}

### Delete the book
DELETE http://localhost:8080/odata/v4/CatalogService/Books(id=1) HTTP/1.1
content-type: application/json