### Create Product

POST http://localhost:8080/odata/v4/AdminService/Products
Content-Type: application/json
Authorization: Basic sabine:pass_sabine

{ "title": "My Tutorial Product", "descr": "You are doing an awesome job!"}

### Read Book

GET http://localhost:8080/odata/v4/BooksService/Books(abed2f7a-c50e-4bc5-89fd-9a00a54b4b16)
Accept: application/json


### Create Categories

POST http://localhost:8080/odata/v4/AdminService/Categories
Content-Type: application/json

{
  "ID": 2,
  "name": "TechEd",
  "descr": "TechEd related topics",
  "children": [
    {
      "ID": 12,
      "name": "CAP Java",
      "descr": "Run on Java"
    },
    {
      "ID": 13,
      "name": "CAP Node.js",
      "descr": "Run on Node.js"
    }
  ]
}

### Create Order as Anne
POST http://localhost:8080/odata/v4/OrdersService/Orders
Content-Type: application/json
Authorization: Basic anne:pass_anne

{
  "items": [
    {
      "book_ID": "abed2f7a-c50e-4bc5-89fd-9a00a54b4b16",
      "amount": 10
    }
  ]
}

### Read Orders as Anne

GET http://localhost:8080/odata/v4/OrdersService/Orders?$expand=items
Accept: application/json
Authorization: Basic anne:pass_anne

