###
# @name IncidentsCreate

GET http://localhost:4004/incidents/Incidents?$select=urgency
##
# 

POST http://localhost:4004/incidents/Incidents
Content-Type: application/json

{
  "title": "Francis",
  "customer_ID": "Francis123"
}

###
@id = {{IncidentsCreate.response.body.$.ID}}

POST http://localhost:4004/incidents/Incidents(ID={{id}},IsActiveEntity=false)/draftActivate
Content-Type: application/json

###
PUT http://localhost:4004/api-business-partner/A_BusinessPartner/Z100001
Authorization: Basic carol:
Content-Type: application/json

{
  "BusinessPartnerFullName": "Albus Percival Wulfric Brian Dumbledore"
}

###
PUT http://localhost:4004/api-business-partner/A_BusinessPartner/Z100002
Authorization: Basic carol:
Content-Type: application/json

{
  "BusinessPartnerFullName": "Albus Percival Wulfric Brian Dumbledore"
}