### Get all Reviews
GET http://admin:admin@localhost:8080/api/browse/Reviews 
### Create a Review
POST http://localhost:8080/api/browse/Reviews 
content-type: application/json

{
  "title": "I hated it",
  "text": "Birds freak me out",
  "rating": 1,
  "book_ID": "51061ce3-ddde-4d70-a2dc-6314afbcc73e"
}
### Get a Review
GET http://admin:admin@localhost:8080/api/browse/Reviews(8089768a-14ae-3cd0-807e-c77ceab8f91e) 
### Update a review
PATCH http://admin:admin@localhost:8080/api/browse/Reviews(8089768a-14ae-3cd0-807e-c77ceab8f91e) 
content-type: application/json
{
  "rating": 2
}
### Delete a rating
DELETE http://admin:admin@localhost:8080/api/browse/Reviews(8089768a-14ae-3cd0-807e-c77ceab8f91e) 
content-type: application/json
### Get all reviews for a book
GET http://admin:admin@localhost:8080/api/browse/Books(f846b0b9-01d4-4f6d-82a4-d79204f62278)/reviews 
content-type: application/json
### Get a single review through a book
GET http://admin:admin@localhost:8080/api/browse/Books(f846b0b9-01d4-4f6d-82a4-d79204f62278)/reviews(8098ea0a-e4b9-3265-9a21-95758a1e49e0) 
content-type: application/json
### Create a review through a book
POST http://admin:admin@localhost:8080/api/browse/Books(f846b0b9-01d4-4f6d-82a4-d79204f62278)/reviews 
content-type: application/json
{
  "title": "I hated it",
  "text": "Birds freak me out",
  "rating": 1
}