### Create a book
POST http://admin:admin@localhost:8080/api/browse/Books(123)/CatalogService.addReview
Content-Type: application/json

{
  "title" : "I hated it",
  "text" : "Birds freak me out",
  "rating" : 3
}