### Get all books
GET http://localhost:8080/api/browse/Books HTTP/1.1

### Create a book
POST http://localhost:8080/api/browse/Books HTTP/1.1
content-type: application/json

{
  "id": 5,
  "title": "Beast",
  "descr": "flop movie",
  "author": "Nelson",
  "genre": "Robbery",
  "rating": 4
}

### Get the book
GET http://localhost:8080/api/browse/Books(id=1) HTTP/1.1

### Update the book
PATCH http://localhost:8080/odata/v4/CatalogService/Books(1) HTTP/1.1
content-type: application/json

{
  "author": "Emily Brontë"
}

### Delete the book
DELETE http://localhost:8080/api/browse/Books(id=5) HTTP/1.1

content-type: application/json


##========================================================###

### Get all Reviews
GET http://admin:admin@localhost:8080/api/browse/Reviews HTTP/1.1

### Create a Review
POST http://admin:admin@localhost:8080/api/browse/Reviews HTTP/1.1
content-type: application/json

{
  "title": "I hated it2",
  "text": "Birds freak me out2",
  "rating": 1,
  "book_id": 3
}
### Get a Review
GET http://admin:admin@localhost:8080/api/browse/Reviews(099843bf-1cb4-4799-aa8a-7342b1eadc5b) HTTP/1.1
### Update a review
PATCH http://admin:admin@localhost:8080/api/browse/Reviews(099843bf-1cb4-4799-aa8a-7342b1eadc5b) HTTP/1.1
content-type: application/json

{
  "rating": 4
}
### Delete a rating
DELETE http://admin:admin@localhost:8080/api/browse/Reviews(cfdf7033-8d23-4bdc-9106-90d8fc2e70ec) HTTP/1.1
content-type: application/json


##========================================================###


### Get all reviews for a book
GET http://admin:admin@localhost:8080/api/browse/Books(3)/reviews HTTP/1.1
content-type: application/json
### Get a single review through a book
GET http://admin:admin@localhost:8080/api/browse/Books(3)/reviews(568625a9-871d-4b24-8de9-5c0416712dd9) HTTP/1.1
content-type: application/json
### Create a review through a book
POST http://admin:admin@localhost:8080/api/browse/Books(111)/reviews HTTP/1.1
content-type: application/json

{
  "title": "I hated it",
  "text": "Birds freak me out",
  "rating": 1
}

### Adding review for book id
POST http://admin:admin@localhost:8080/api/browse/Books(1)/CatalogService.addReview
content-type: application/json

{
  "title": "I hated ittest",
  "text": "Birds freak me outtest",
  "rating": 1
}


### Adding review for book id
GET http://admin:admin@localhost:8080/api/browse/Reviews(f579534f-892f-4ec0-90b3-7d8a7bdb6cec) HTTP/1.1
content-type: application/json


