### Get all books
GET http://localhost:8080/api/browse/Books HTTP/1.1


### Create a book
POST http://localhost:8080/api/browse/Books HTTP/1.1



{
  "id": "118",
  "title": "sap",
  "descr": "btp reference",
  "author": "anu",
  "genre": "Education",
  "price": 1000.00,
  "currency_code": "USD",
  "rating": 5.0
}





### Get the book
GET http://localhost:8080/api/browse/Books('118') HTTP/1.1


### Update the book
PATCH http://localhost:8080/api/browse/Books('118') HTTP/1.1
content-type: application/json

{
  "author": "Emily Brontë"
}

### Delete the book
DELETE http://localhost:8080/api/browse/Books('112') HTTP/1.1
content-type: application/json

### Get all Reviews
GET http://localhost:8080/api/browse/Reviews HTTP/1.1


### Create a Review
POST http://localhost:8080/api/browse/Reviews HTTP/1.1
# Content-Type: application/json
# Authorization: Basic authenticated:
# Content-Type: application/json
# Authorization: Basic mia:pass_mia
Content-Type: application/json
Authorization: Basic sabine:pass_sabine

{
  "title": "I hated it",
  "text": "Birds freak me out",
  "rating": 1,
  "book_id": "121"
}

### Get a Review
GET http://localhost:8080/api/browse/Reviews(1f5831cf-7f0c-4bde-bdfa-83bc05123bcc) HTTP/1.1

### Update a review
PATCH http://localhost:8080/api/browse/Reviews(1f5831cf-7f0c-4bde-bdfa-83bc05123bcc) HTTP/1.1
content-type: application/json

{
  "rating": 2
}

### Delete a rating
DELETE http://localhost:8080/api/browse/Reviews(1f5831cf-7f0c-4bde-bdfa-83bc05123bcc) HTTP/1.1
content-type: application/json

### Get all reviews for a book
GET http://admin:admin@localhost:8080/api/browse/Books('121')/reviews HTTP/1.1
content-type: application/json

### Get a single review through a book
GET http://localhost:8080/api/browse/Books('121')/reviews(1f5831cf-7f0c-4bde-bdfa-83bc05123bcc) HTTP/1.1
content-type: application/json

### Create a review through a book
POST http://localhost:8080/api/browse/Books('118')/CatalogService.addReview 
Content-type: application/json

{
  "title": "I hated it",
  "text": "Birds freak me out",
  "rating": 1
}