### Get all books
GET http://localhost:8080/odata/v4/CatalogService/Books HTTP/1.1
### Create a book
POST http://admin:admin@localhost:8080/api/browse/Books HTTP/1.1
content-type: application/json

{
  "id": 8,
  "title": "Wuthering Heights",
  
  "author": "Jane Austen",
  "genre": "Drama",
  "rating": 4
}
### Get the book
GET http://localhost:8080/odata/v4/CatalogService/Books(id=1) HTTP/1.1
### Update the book
PATCH http://localhost:8080/odata/v4/CatalogService/Books(1) HTTP/1.1
content-type: application/json
{
  "author": "Emily Brontë"
}
### Delete the book
DELETE http://localhost:8080/odata/v4/CatalogService/Books(id=1) HTTP/1.1
content-type: application/json


### Get all Reviews
GET http://admin:admin@localhost:8080/api/browse/Reviews HTTP/1.1
### Create a Review
POST http://admin:admin@localhost:8080/api/browse/Reviews HTTP/1.1
content-type: application/json

{
  "title": "I hated it",
  "text": "Birds freak me out",
  "rating": 4,
  "book_id": "111" 
}
### Get a Review
GET http://admin:admin@localhost:8080/api/browse/Reviews(3be64ef9-46cd-46c2-816c-24dc94e8bab9) HTTP/1.1
### Update a review
PATCH http://admin:admin@localhost:8080/api/browse/Reviews(8089768a-14ae-3cd0-807e-c77ceab8f91e) HTTP/1.1
content-type: application/json
{
  "rating": 2
}
### Delete a rating
DELETE http://admin:admin@localhost:8080/api/browse/Reviews(8089768a-14ae-3cd0-807e-c77ceab8f91e) HTTP/1.1
content-type: application/json
### Get all reviews for a book
GET http://admin:admin@localhost:8080/api/browse/Books(f846b0b9-01d4-4f6d-82a4-d79204f62278)/reviews HTTP/1.1
content-type: application/json
### Get a single review through a book
GET http://admin:admin@localhost:8080/api/browse/Books(f846b0b9-01d4-4f6d-82a4-d79204f62278)/reviews(8098ea0a-e4b9-3265-9a21-95758a1e49e0) HTTP/1.1
content-type: application/json
### Create a review through a book
POST http://admin:admin@localhost:8080/api/browse/Books(6)/reviews HTTP/1.1
content-type: application/json

{
  "title": "I hated it",
  "text": "Birds freak me out",
  "rating": 1
}
content-length: 80
### Create a review through AddReview Button
POST http://localhost:8080/api/browse/Books(6)/CatalogService.addReview HTTP/1.1
content-type: application/json

{
  "title": "I hated it",
  "text": "Birds freak me out",
  "rating": 2
}


### Get the new Review
GET http://admin:admin@localhost:8080/api/browse/Reviews(1244d87b-a395-4785-8856-15a43df6e923) HTTP/1.1