### Create Product

POST http://localhost:8080/odata/v4/SpeedService/SampleProduct
Content-Type: application/json

{
  "ID": 2,
  "title": "Sample Product 2",
  "descr": "This is a sample description for Product 1"
}



